jobs: 100
reason: True
use-conda: True
latency-wait: 60
printshellcmds: True
show-failed-logs: True
rerun-incomplete: True
restart-times: 3
cluster: "sbatch --parsable  -t {resources.time} --mem={resources.mem_mb} -c {resources.cpus} -o {log.cluster_log} -e {log.cluster_err}"
